import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
// import ThemeProvider from "@/theme/theme-provider";

// 메타데이터는 별도의 파일이나 레이아웃 외부에 정의해야 합니다
// 클라이언트 컴포넌트에서는 직접 메타데이터를 내보낼 수 없습니다
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark:bg-black">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <div className="max-w-[620px] mx-auto">
          {/* mx-auto : 좌우 여백 동일 */}
          {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > */}
          <Navbar />
          {children}
          <Footer />
          {/* </ThemeProvider> */}
        </div>
      </body>
    </html>
  );
}
